#image: "jojomi/hugo:0.85.0"
#image: "klakegg/hugo:0.106.0-ubuntu"
image: "cibuilds/hugo:0.111.3"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_BASEURL: https://blog.ipspace.net
  TZ: Europe/Berlin

pages:
  script:
  - hugo version
  - hugo
  artifacts:
    expire_in: 180 seconds
    paths:
    - public
  only:
  - publish
