image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_BASEURL: https://blog.ipspace.net
  TZ: Europe/Berlin

pages:
  script:
  - hugo version
  - hugo
  artifacts:
    paths:
    - public
  only:
  - publish
