#!/bin/bash
#
# Create local publish branch if needed
#
if [ -z "`git branch -v|grep publish`" ]; then
  echo "Local publish branch is missing, creating..."
  git checkout -b publish origin/publish
fi
git checkout publish 2>&1|ack -v "Already|up to date"
POPULAR_BEFORE=`ls -l data/popular.json`
if [ "$1" = "test" ]; then
  echo "Test run, merging local branches..."
  git merge master
else
  git fetch --all --force|ack -v "Already|Fetching"
  git merge origin/publish -X theirs|ack -v "Already|Fetching"
  git merge origin/master -X theirs|ack -v "up to date"
fi
POPULAR_AFTER=`ls -l data/popular.json`
if [ "$POPULAR_BEFORE" != "$POPULAR_AFTER" ]; then
  echo "Merge changed popular blog post list, rebuilding..."
  tools/create-popular.py
fi
tools/create-archive.py --quiet
tools/create-comments.py
if [ -z "`find data -name 'popular.json' -mmin -480 -print`" ]; then
  tools/create-popular.py
fi
git add . -v
if [ "$1" = "test" ]; then
  echo "Test run, not pushing the changes..."
else
  if [ -n "`git status --short`" ]; then
    git commit -m 'Master merge + update' 2>&1
  fi
  git push 2>&1|ack -vi "up-to-date"
fi
